### ISSUE TITLE
Make SEP request context paths configurable

### ISSUE THREAD

**Issue by lijamie98** [stellar/java-stellar-anchor-sdk#131]
The current SEP context paths are hard-coded. We should make them configurable as the following YAML example.

```yaml
sep12:
  enabled: true
  path: /sep12

sep24:
  enabled: true
  path: /sep24

sep31:
  enabled: true
  path: /sep31

sep38:
  enabled: true
  path: /sep38
```
