### ISSUE TITLE
NPE on client attribution 

### ISSUE THREAD

**Issue by Ifropc** [stellar/java-stellar-anchor-sdk#1438]
Reported by a community member on Discord 

I am still finding it difficult to understand fully how the Client Attribution works, this time custodial authentication was working perfectly, but I could no longer authenticate again with a noncustodial wallet.

services.yaml clients configuration

```
   version: 1
    sep10:
      client_allow_list: ["demo-wallet-01", "demo-wallet-02"]
      client_attribution_required: true
    clients:
      - type: custodial
        name: "demo-wallet-01"
        signing_keys: "GACHLSMHOK64PE3CHHASSNFSZX5YGPJZ3ODQIFEPLS6JWS624SPQP4TA" 
      - type: noncustodial
        name: "demo-wallet-02"
        domains: "demo-wallet-server.stellar.org"
```

I have also tried changing the domains in services.yaml to demo-wallet.stellar.org still the same error

```
{
    "error": "Cannot invoke \"java.util.Set.stream()\" because the return value of \"org.stellar.anchor.config.ClientsConfig$ClientConfig.getDomains()\" is null"
}
```

![image](https://github.com/user-attachments/assets/62b0a157-0f68-4d56-9913-3f88222e74b9)
![image](https://github.com/user-attachments/assets/160b8ffa-344f-415c-958f-d49aa17e46b9)

https://discord.com/channels/897514728459468821/961080541711568966/1263431912266006528
